import turtle
import time
t = turtle.Turtle()
t.speed(10)
t.penup()
t.right(90)
t.forward(100)
t.pendown()
t.left(90)
t.circle(200)
t.left(90)
t.forward(400)
t.left(180)
t.forward(200)
t.right(90)
t.forward(200)
t.left(180)
t.forward(400)
t.left(180)
t.forward(200)
t.left(30)
t.forward(200)
t.backward(200)
t.left(30)
t.forward(200)
t.backward(200)
t.left(60)
t.forward(200)
t.backward(200)
t.left(30)
t.forward(200)
t.backward(200)
t.left(60)
t.forward(200)
t.backward(200)
t.left(30)
t.forward(200)
t.backward(200)
t.left(60)
t.forward(200)
t.backward(200)
t.left(30)
t.forward(200)
t.backward(200)
t.forward(100)
t.left(90)
t.circle(100)
t.penup()
t.left(90)
t.forward(100)
t.left(30)
t.forward(175)
t.left(90)
t.left(45)
t.forward(45)
t.write('D',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.right(30)
t.forward(70)
t.write('G',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(30)
t.forward(70)
t.left(60)
t.forward(25)
t.write('C',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.right(10)
t.forward(75)
t.write('F',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(15)
t.forward(85)
t.write('Bb',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(40)
t.forward(85)
t.write('Eb',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(25)
t.forward(85)
t.write('Ab',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(45)
t.forward(80)
t.write('Db , C#',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(35)
t.forward(75)
t.write('Gb , F#',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(10)
t.forward(75)
t.write('B , Cb',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(30)
t.forward(65)
t.write('E',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(30)
t.forward(65)
t.write('A',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(105)
t.forward(90)
t.write('F#m',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.right(90)
t.forward(40)
t.write('Bm',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(45)
t.forward(40)
t.write('Em',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(45)
t.forward(40)
t.write('Am',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(30)
t.forward(40)
t.write('Dm',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(30)
t.forward(35)
t.write('Gm',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(30)
t.forward(35)
t.write('Cm',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(30)
t.forward(35)
t.write('Fm',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(30)
t.forward(35)
t.write('Bbm',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(30)
t.forward(30)
t.write('Ebm',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(30)
t.forward(35)
t.write('G#m',False,align="center",font = ("Comic Sans", 16 ,"normal"))
t.left(30)
t.forward(27)
t.write('C#m',False,align="center",font = ("Comic Sans", 16 ,"normal"))

time.sleep(300)


